# Generated by Django 4.2.3 on 2024-01-29 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('rname', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meetingnum', models.IntegerField(default=0)),
                ('readynum', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('kid', models.BigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='menInfo',
            fields=[
                ('mkid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.userinfo')),
                ('nickname', models.TextField()),
                ('age', models.IntegerField(null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('army', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('eyes', models.CharField(blank=True, max_length=10, null=True)),
                ('face', models.CharField(blank=True, max_length=10, null=True)),
                ('hobby', models.CharField(blank=True, max_length=100, null=True)),
                ('animal', models.CharField(blank=True, max_length=20, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('avgage', models.IntegerField(null=True)),
                ('w_age', models.CharField(blank=True, max_length=50, null=True)),
                ('w_job', models.CharField(blank=True, max_length=50, null=True)),
                ('w_school', models.CharField(blank=True, max_length=50, null=True)),
                ('w_major', models.CharField(blank=True, max_length=50, null=True)),
                ('w_mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('w_height', models.IntegerField(blank=True, null=True)),
                ('w_body', models.CharField(blank=True, max_length=10, null=True)),
                ('w_eyes', models.CharField(blank=True, max_length=10, null=True)),
                ('w_face', models.CharField(blank=True, max_length=10, null=True)),
                ('w_hobby', models.CharField(blank=True, max_length=100, null=True)),
                ('w_animal', models.CharField(blank=True, max_length=20, null=True)),
                ('free', models.TextField(blank=True, null=True)),
                ('kakaotalk_id', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(blank=True, max_length=20, null=True)),
                ('coin', models.IntegerField(default=0)),
                ('rno', models.ForeignKey(blank=True, db_column='rno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_infos', to='common.room')),
            ],
        ),
        migrations.CreateModel(
            name='womenInfo',
            fields=[
                ('wkid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.userinfo')),
                ('nickname', models.TextField()),
                ('age', models.IntegerField(null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('eyes', models.CharField(blank=True, max_length=10, null=True)),
                ('face', models.CharField(blank=True, max_length=10, null=True)),
                ('hobby', models.CharField(blank=True, max_length=100, null=True)),
                ('animal', models.CharField(blank=True, max_length=20, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('avgage', models.IntegerField(null=True)),
                ('m_age', models.CharField(blank=True, max_length=50, null=True)),
                ('m_job', models.CharField(blank=True, max_length=50, null=True)),
                ('m_school', models.CharField(blank=True, max_length=50, null=True)),
                ('m_major', models.CharField(blank=True, max_length=50, null=True)),
                ('m_mbti', models.CharField(blank=True, max_length=10, null=True)),
                ('m_army', models.CharField(blank=True, max_length=10, null=True)),
                ('m_height', models.IntegerField(blank=True, null=True)),
                ('m_body', models.CharField(blank=True, max_length=10, null=True)),
                ('m_eyes', models.CharField(blank=True, max_length=10, null=True)),
                ('m_face', models.CharField(blank=True, max_length=10, null=True)),
                ('m_hobby', models.CharField(blank=True, max_length=100, null=True)),
                ('m_animal', models.CharField(blank=True, max_length=20, null=True)),
                ('free', models.TextField(blank=True, null=True)),
                ('kakaotalk_id', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(blank=True, max_length=20, null=True)),
                ('coin', models.IntegerField(default=0)),
                ('mkid', models.ForeignKey(blank=True, db_column='mkid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.meninfo')),
                ('rno', models.ForeignKey(blank=True, db_column='rno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='women_infos', to='common.room')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='womenParty',
            fields=[
                ('pnum', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('animal', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('wkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_party', to='common.womeninfo')),
            ],
        ),
        migrations.CreateModel(
            name='menParty',
            fields=[
                ('pnum', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField(null=True)),
                ('animal', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, max_length=10, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('mkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men_party', to='common.meninfo')),
            ],
        ),
        migrations.AddField(
            model_name='meninfo',
            name='wkid',
            field=models.ForeignKey(blank=True, db_column='wkid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.womeninfo'),
        ),
        migrations.CreateModel(
            name='matchingInfo',
            fields=[
                ('matchingnum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rno', models.ForeignKey(blank=True, db_column='rno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.room')),
                ('mkid', models.ForeignKey(blank=True, db_column='mkid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.meninfo')),
                ('wkid', models.ForeignKey(blank=True, db_column='wkid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.womeninfo')),
            ],
        ),
    ]
