# Generated by Django 4.2.3 on 2024-02-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='gender',
            new_name='ismale',
        ),
    ]
