# Generated by Django 4.2.3 on 2024-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meninfo',
            name='w_height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='m_height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
