# Generated by Django 4.2.3 on 2024-02-01 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='mkid',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='wkid',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
