# Generated by Django 4.2.3 on 2024-01-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_room_iminfo_remove_room_iwinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meninfo',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='meninfo',
            name='w_army',
        ),
        migrations.RemoveField(
            model_name='womeninfo',
            name='army',
        ),
        migrations.RemoveField(
            model_name='womeninfo',
            name='notice',
        ),
        migrations.AddField(
            model_name='meninfo',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='womeninfo',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='womenNotice',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.womeninfo')),
            ],
        ),
        migrations.CreateModel(
            name='menNotice',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.meninfo')),
            ],
        ),
    ]
