# Generated by Django 4.2.3 on 2024-02-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_room_options_notice_readed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menparty',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='womenparty',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
