# Generated by Django 4.2.3 on 2024-02-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_notice_options_alter_meninfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meninfo',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='womeninfo',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
