# Generated by Django 4.2.3 on 2024-02-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_meninfo_location_womeninfo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='each_match',
            field=models.IntegerField(default=0),
        ),
    ]
