# Generated by Django 4.2.3 on 2024-03-08 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_menparty_nickname_womenparty_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matched_user', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchingHistory_userInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='matchingInfo',
        ),
    ]
