# Generated by Django 4.2.3 on 2024-01-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_meninfo_notice_remove_meninfo_w_army_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meninfo',
            name='rno',
            field=models.ForeignKey(blank=True, db_column='rno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='men_infos', to='common.room'),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='rno',
            field=models.ForeignKey(blank=True, db_column='rno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='women_infos', to='common.room'),
        ),
    ]
