# Generated by Django 4.2.3 on 2024-01-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_meninfo_rno_alter_womeninfo_rno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menparty',
            name='mkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men_party', to='common.meninfo'),
        ),
        migrations.AlterField(
            model_name='womenparty',
            name='wkid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='women_party', to='common.womeninfo'),
        ),
    ]
