# Generated by Django 4.2.3 on 2024-01-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_menparty_mkid_alter_womenparty_wkid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='mnum',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wnum',
        ),
    ]
