# Generated by Django 4.2.3 on 2024-03-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_userinfo_ismale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ismale',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
