# Generated by Django 4.2.3 on 2024-01-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_room_mnum_remove_room_wnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='menparty',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
