# Generated by Django 4.2.3 on 2024-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_userinfo_ismale'),
    ]

    operations = [
        migrations.AddField(
            model_name='meninfo',
            name='keyword',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meninfo',
            name='face',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meninfo',
            name='hobby',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
