# Generated by Django 4.2.3 on 2024-01-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_menparty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='womenparty',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
