# Generated by Django 4.2.3 on 2024-03-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_meninfo_keyword_alter_meninfo_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='womeninfo',
            name='keyword',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meninfo',
            name='w_face',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='face',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='hobby',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='m_face',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
