# Generated by Django 4.2.3 on 2024-01-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_womenparty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meninfo',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='womeninfo',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
