# Generated by Django 4.2.3 on 2024-01-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_meninfo_ready_alter_womeninfo_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menparty',
            name='location',
        ),
        migrations.RemoveField(
            model_name='womenparty',
            name='location',
        ),
        migrations.AddField(
            model_name='menparty',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
