# Generated by Django 4.2.3 on 2024-01-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_remove_menparty_location_remove_womenparty_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
